# This is a TOML document.

title = "TOML Example"
owner = { name = "Tom Preston-Werner", dob = 1979-05-27T07:32:00-08:00 } # Inline table and date

[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true
# hex_val = 0xDEAD_BEEF # Example integer types
# bin_val = 0b11010110
# float_val = 6.626e-34

[servers] # Empty table initially

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[[products]] # Array of Tables
name = "Hammer"
sku = 738594937

[[products]]
name = "Nail"
sku = 284758393
color = "gray"

# clients.data = [ ["gamma", "delta"], [1, 2] ] # Nested array
# Line breaks are OK when inside arrays
# hosts = [
#  "alpha",
#  "omega"
# ] 

# --- Added for scanner test ---

basic_multiline = """
Roses are red
Violets are blue"""

# Line ending backslash test
line_ending_backslash = """
The quick brown \


  fox jumps over \
    the lazy dog."""

literal_multiline = '''
The first newline is
trimmed in raw strings.
   All other whitespace
   is preserved.
'''

# Test quotes inside
quotes_inside_basic = """Here are two quotation marks: "". Simple enough."""
quotes_inside_literal = '''Here are fifteen quotation marks: """""""""""""""''' 