/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 113
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 1
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__newline = 1,
  sym_comment = 2,
  anon_sym_EQ = 3,
  sym_bare_key = 4,
  anon_sym_DOT = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  anon_sym_LBRACK_LBRACK = 8,
  anon_sym_RBRACK_RBRACK = 9,
  anon_sym_DQUOTE = 10,
  aux_sym__basic_string_inline_token1 = 11,
  anon_sym_SQUOTE = 12,
  aux_sym__literal_string_inline_token1 = 13,
  anon_sym_DQUOTE_DQUOTE_DQUOTE = 14,
  anon_sym_SQUOTE_SQUOTE_SQUOTE = 15,
  sym_escape_sequence = 16,
  sym_integer = 17,
  sym_float = 18,
  sym_boolean = 19,
  sym_date_time = 20,
  anon_sym_COMMA = 21,
  anon_sym_LBRACE = 22,
  anon_sym_RBRACE = 23,
  sym__multiline_basic_string_content = 24,
  sym__multiline_literal_string_content = 25,
  sym_source_file = 26,
  sym__expression = 27,
  sym_key_value = 28,
  sym_key = 29,
  sym__simple_key = 30,
  sym_quoted_key = 31,
  sym_dotted_key = 32,
  sym_table = 33,
  sym_array_of_tables = 34,
  sym__value = 35,
  sym_string = 36,
  sym__basic_string_inline = 37,
  sym__literal_string_inline = 38,
  sym__multiline_basic_string = 39,
  sym__multiline_literal_string = 40,
  sym_array = 41,
  sym_inline_table = 42,
  sym_inline_key_value = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym__basic_string_inline_repeat1 = 45,
  aux_sym__literal_string_inline_repeat1 = 46,
  aux_sym__multiline_basic_string_repeat1 = 47,
  aux_sym__multiline_literal_string_repeat1 = 48,
  aux_sym_array_repeat1 = 49,
  aux_sym_inline_table_repeat1 = 50,
  alias_sym_string_content = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__newline] = "_newline",
  [sym_comment] = "comment",
  [anon_sym_EQ] = "=",
  [sym_bare_key] = "bare_key",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [anon_sym_RBRACK_RBRACK] = "]]",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__basic_string_inline_token1] = "_basic_string_inline_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__literal_string_inline_token1] = "_literal_string_inline_token1",
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = "\"\"\"",
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = "'''",
  [sym_escape_sequence] = "escape_sequence",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [sym_boolean] = "boolean",
  [sym_date_time] = "date_time",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym__multiline_basic_string_content] = "_multiline_basic_string_content",
  [sym__multiline_literal_string_content] = "_multiline_literal_string_content",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym_key_value] = "key_value",
  [sym_key] = "key",
  [sym__simple_key] = "_simple_key",
  [sym_quoted_key] = "quoted_key",
  [sym_dotted_key] = "dotted_key",
  [sym_table] = "table",
  [sym_array_of_tables] = "array_of_tables",
  [sym__value] = "_value",
  [sym_string] = "string",
  [sym__basic_string_inline] = "_basic_string_inline",
  [sym__literal_string_inline] = "_literal_string_inline",
  [sym__multiline_basic_string] = "_multiline_basic_string",
  [sym__multiline_literal_string] = "_multiline_literal_string",
  [sym_array] = "array",
  [sym_inline_table] = "inline_table",
  [sym_inline_key_value] = "inline_key_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__basic_string_inline_repeat1] = "_basic_string_inline_repeat1",
  [aux_sym__literal_string_inline_repeat1] = "_literal_string_inline_repeat1",
  [aux_sym__multiline_basic_string_repeat1] = "_multiline_basic_string_repeat1",
  [aux_sym__multiline_literal_string_repeat1] = "_multiline_literal_string_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_inline_table_repeat1] = "inline_table_repeat1",
  [alias_sym_string_content] = "string_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__newline] = sym__newline,
  [sym_comment] = sym_comment,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_bare_key] = sym_bare_key,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [anon_sym_RBRACK_RBRACK] = anon_sym_RBRACK_RBRACK,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__basic_string_inline_token1] = aux_sym__basic_string_inline_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__literal_string_inline_token1] = aux_sym__literal_string_inline_token1,
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE_DQUOTE,
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = anon_sym_SQUOTE_SQUOTE_SQUOTE,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [sym_boolean] = sym_boolean,
  [sym_date_time] = sym_date_time,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__multiline_basic_string_content] = sym__multiline_basic_string_content,
  [sym__multiline_literal_string_content] = sym__multiline_literal_string_content,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym_key_value] = sym_key_value,
  [sym_key] = sym_key,
  [sym__simple_key] = sym__simple_key,
  [sym_quoted_key] = sym_quoted_key,
  [sym_dotted_key] = sym_dotted_key,
  [sym_table] = sym_table,
  [sym_array_of_tables] = sym_array_of_tables,
  [sym__value] = sym__value,
  [sym_string] = sym_string,
  [sym__basic_string_inline] = sym__basic_string_inline,
  [sym__literal_string_inline] = sym__literal_string_inline,
  [sym__multiline_basic_string] = sym__multiline_basic_string,
  [sym__multiline_literal_string] = sym__multiline_literal_string,
  [sym_array] = sym_array,
  [sym_inline_table] = sym_inline_table,
  [sym_inline_key_value] = sym_inline_key_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__basic_string_inline_repeat1] = aux_sym__basic_string_inline_repeat1,
  [aux_sym__literal_string_inline_repeat1] = aux_sym__literal_string_inline_repeat1,
  [aux_sym__multiline_basic_string_repeat1] = aux_sym__multiline_basic_string_repeat1,
  [aux_sym__multiline_literal_string_repeat1] = aux_sym__multiline_literal_string_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_inline_table_repeat1] = aux_sym_inline_table_repeat1,
  [alias_sym_string_content] = alias_sym_string_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_bare_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__basic_string_inline_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__literal_string_inline_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_date_time] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__multiline_basic_string_content] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_literal_string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_key_value] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym__simple_key] = {
    .visible = false,
    .named = true,
  },
  [sym_quoted_key] = {
    .visible = true,
    .named = true,
  },
  [sym_dotted_key] = {
    .visible = true,
    .named = true,
  },
  [sym_table] = {
    .visible = true,
    .named = true,
  },
  [sym_array_of_tables] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__basic_string_inline] = {
    .visible = false,
    .named = true,
  },
  [sym__literal_string_inline] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_basic_string] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_literal_string] = {
    .visible = false,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_table] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_key_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__basic_string_inline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__literal_string_inline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__multiline_basic_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__multiline_literal_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_inline_table_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_string_content] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_member_key = 2,
  field_name = 3,
  field_table_key = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_member_key] = "member_key",
  [field_name] = "name",
  [field_table_key] = "table_key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 2},
  [4] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_key, 0},
    {field_value, 2},
  [3] =
    {field_member_key, 2},
    {field_table_key, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_string,
  },
  [5] = {
    [1] = alias_sym_string_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__basic_string_inline, 2,
    sym__basic_string_inline,
    sym_string,
  sym__literal_string_inline, 2,
    sym__literal_string_inline,
    sym_string,
  aux_sym__multiline_basic_string_repeat1, 2,
    aux_sym__multiline_basic_string_repeat1,
    alias_sym_string_content,
  aux_sym__multiline_literal_string_repeat1, 2,
    aux_sym__multiline_literal_string_repeat1,
    alias_sym_string_content,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 18,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 25,
  [29] = 26,
  [30] = 25,
  [31] = 26,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 32,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 44,
  [59] = 38,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 34,
  [64] = 36,
  [65] = 37,
  [66] = 60,
  [67] = 39,
  [68] = 43,
  [69] = 61,
  [70] = 70,
  [71] = 44,
  [72] = 38,
  [73] = 73,
  [74] = 23,
  [75] = 33,
  [76] = 76,
  [77] = 21,
  [78] = 22,
  [79] = 24,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 70,
  [89] = 42,
  [90] = 51,
  [91] = 47,
  [92] = 53,
  [93] = 49,
  [94] = 73,
  [95] = 95,
  [96] = 96,
  [97] = 54,
  [98] = 50,
  [99] = 55,
  [100] = 100,
  [101] = 56,
  [102] = 100,
  [103] = 48,
  [104] = 57,
  [105] = 105,
  [106] = 52,
  [107] = 24,
  [108] = 21,
  [109] = 22,
  [110] = 110,
  [111] = 111,
  [112] = 23,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(70);
      ADVANCE_MAP(
        '"', 98,
        '#', 72,
        '\'', 102,
        '+', 12,
        ',', 130,
        '-', 74,
        '.', 91,
        '0', 80,
        '=', 73,
        '[', 93,
        '\\', 19,
        ']', 94,
        'f', 79,
        't', 83,
        '{', 131,
        '}', 132,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(69);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(71);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(97);
      if (lookahead == '#') ADVANCE(72);
      if (lookahead == '\'') ADVANCE(101);
      if (lookahead == '[') ADVANCE(93);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(7);
      if (lookahead == '"') ADVANCE(97);
      if (lookahead == '#') ADVANCE(100);
      if (lookahead == '\\') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(100);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(8);
      if (lookahead == '#') ADVANCE(104);
      if (lookahead == '\'') ADVANCE(101);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(104);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '"', 98,
        '#', 72,
        '\'', 102,
        ',', 130,
        '0', 114,
        '[', 92,
        ']', 94,
        'f', 21,
        'i', 26,
        'n', 22,
        't', 28,
        '{', 131,
        '+', 13,
        '-', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(111);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(105);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(97);
      if (lookahead == '#') ADVANCE(72);
      if (lookahead == '\'') ADVANCE(101);
      if (lookahead == '.') ADVANCE(91);
      if (lookahead == ']') ADVANCE(20);
      if (lookahead == '}') ADVANCE(132);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(97);
      if (lookahead == '#') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == '#') ADVANCE(72);
      if (lookahead == '\'') ADVANCE(101);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      END_STATE();
    case 9:
      if (lookahead == '\'') ADVANCE(106);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(53);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(48);
      END_STATE();
    case 12:
      if (lookahead == '0') ADVANCE(108);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(116);
      END_STATE();
    case 13:
      if (lookahead == '0') ADVANCE(115);
      if (lookahead == 'i') ADVANCE(26);
      if (lookahead == 'n') ADVANCE(22);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(47);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(49);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(50);
      END_STATE();
    case 18:
      if (lookahead == ':') ADVANCE(56);
      END_STATE();
    case 19:
      ADVANCE_MAP(
        'U', 67,
        'u', 63,
        '"', 107,
        '\\', 107,
        'b', 107,
        'f', 107,
        'n', 107,
        'r', 107,
        't', 107,
      );
      END_STATE();
    case 20:
      if (lookahead == ']') ADVANCE(96);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(123);
      END_STATE();
    case 24:
      if (lookahead == 'f') ADVANCE(120);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(120);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 31:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(122);
      END_STATE();
    case 32:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(117);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(118);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(122);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 39:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 40:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(128);
      END_STATE();
    case 42:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      END_STATE();
    case 43:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      END_STATE();
    case 44:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      END_STATE();
    case 45:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 46:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 47:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 56:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 57:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 58:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 59:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(107);
      END_STATE();
    case 60:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(119);
      END_STATE();
    case 61:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(59);
      END_STATE();
    case 62:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(61);
      END_STATE();
    case 63:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(62);
      END_STATE();
    case 64:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(63);
      END_STATE();
    case 65:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(64);
      END_STATE();
    case 66:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(65);
      END_STATE();
    case 67:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(66);
      END_STATE();
    case 68:
      if (eof) ADVANCE(70);
      if (lookahead == '\n') ADVANCE(71);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(97);
      if (lookahead == '#') ADVANCE(72);
      if (lookahead == '\'') ADVANCE(101);
      if (lookahead == '[') ADVANCE(93);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(68);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 69:
      if (eof) ADVANCE(70);
      ADVANCE_MAP(
        '"', 98,
        '#', 72,
        '\'', 102,
        '+', 12,
        ',', 130,
        '-', 74,
        '.', 91,
        '0', 80,
        '=', 73,
        '[', 93,
        ']', 94,
        'f', 79,
        't', 83,
        '{', 131,
        '}', 132,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(69);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(71);
      if (lookahead == '\r') ADVANCE(1);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == '0') ADVANCE(90);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(78);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == '_') ADVANCE(86);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(75);
      if (lookahead == '-' ||
          ('2' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == '_') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(76);
      if (lookahead == '-' ||
          lookahead == '8' ||
          lookahead == '9' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == '_') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(77);
      if (lookahead == '-' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == '_') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == 'a') ADVANCE(82);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == 'b') ADVANCE(86);
      if (lookahead == 'o') ADVANCE(87);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(89);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == 'e') ADVANCE(90);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == 'l') ADVANCE(84);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == 'r') ADVANCE(85);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == 's') ADVANCE(81);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == 'u') ADVANCE(81);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(75);
      if (lookahead == '-' ||
          ('2' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_bare_key);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(76);
      if (lookahead == '-' ||
          lookahead == '8' ||
          lookahead == '9' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_bare_key);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_bare_key);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(77);
      if (lookahead == '-' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_bare_key);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '[') ADVANCE(95);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '"') ADVANCE(5);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym__basic_string_inline_token1);
      if (lookahead == '#') ADVANCE(100);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '\\') ADVANCE(100);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym__basic_string_inline_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '%' &&
          lookahead != '\\') ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\'') ADVANCE(9);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym__literal_string_inline_token1);
      if (lookahead == '#') ADVANCE(104);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(103);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '%' &&
          lookahead != '\'') ADVANCE(104);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym__literal_string_inline_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '%' &&
          lookahead != '\'') ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE_DQUOTE);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_SQUOTE_SQUOTE_SQUOTE);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_integer);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '-') ADVANCE(53);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == '_') ADVANCE(45);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == ':') ADVANCE(46);
      if (lookahead == '_') ADVANCE(45);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == '_') ADVANCE(45);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(110);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == '_') ADVANCE(45);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(109);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == '_') ADVANCE(45);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == 'b') ADVANCE(32);
      if (lookahead == 'o') ADVANCE(33);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(31);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '_') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '_') ADVANCE(32);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(117);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '_') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(118);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '_') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(119);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_float);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(35);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '_') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(122);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_boolean);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_date_time);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_date_time);
      if (lookahead == '.') ADVANCE(40);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_date_time);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == 'Z') ADVANCE(124);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(58);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_date_time);
      if (lookahead == 'Z') ADVANCE(124);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_date_time);
      if (lookahead == ' ' ||
          lookahead == 'T') ADVANCE(54);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_date_time);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 68},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 68},
  [10] = {.lex_state = 68},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 68},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 0, .external_lex_state = 2},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 3},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0, .external_lex_state = 2},
  [41] = {.lex_state = 0, .external_lex_state = 3},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 0, .external_lex_state = 2},
  [61] = {.lex_state = 0, .external_lex_state = 3},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0, .external_lex_state = 3},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0, .external_lex_state = 2},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0, .external_lex_state = 3},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 6},
  [75] = {.lex_state = 6},
  [76] = {.lex_state = 0, .external_lex_state = 3},
  [77] = {.lex_state = 6},
  [78] = {.lex_state = 6},
  [79] = {.lex_state = 6},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 6},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0, .external_lex_state = 2},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 6},
  [89] = {.lex_state = 6},
  [90] = {.lex_state = 68},
  [91] = {.lex_state = 68},
  [92] = {.lex_state = 68},
  [93] = {.lex_state = 68},
  [94] = {.lex_state = 68},
  [95] = {.lex_state = 68},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 68},
  [98] = {.lex_state = 68},
  [99] = {.lex_state = 68},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 68},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 68},
  [104] = {.lex_state = 68},
  [105] = {.lex_state = 68},
  [106] = {.lex_state = 68},
  [107] = {.lex_state = 68},
  [108] = {.lex_state = 68},
  [109] = {.lex_state = 68},
  [110] = {.lex_state = 68},
  [111] = {.lex_state = 68},
  [112] = {.lex_state = 68},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_bare_key] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE_DQUOTE_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym__multiline_basic_string_content] = ACTIONS(1),
    [sym__multiline_literal_string_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(96),
    [sym__expression] = STATE(95),
    [sym_key_value] = STATE(95),
    [sym_key] = STATE(87),
    [sym__simple_key] = STATE(70),
    [sym_quoted_key] = STATE(70),
    [sym_dotted_key] = STATE(70),
    [sym_table] = STATE(95),
    [sym_array_of_tables] = STATE(95),
    [sym__basic_string_inline] = STATE(42),
    [sym__literal_string_inline] = STATE(42),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [sym_bare_key] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_RBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    ACTIONS(33), 1,
      anon_sym_COMMA,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 3,
      sym_float,
      sym_boolean,
      sym_date_time,
    STATE(34), 4,
      sym__value,
      sym_string,
      sym_array,
      sym_inline_table,
    STATE(47), 4,
      sym__basic_string_inline,
      sym__literal_string_inline,
      sym__multiline_basic_string,
      sym__multiline_literal_string,
  [48] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    ACTIONS(39), 1,
      sym_integer,
    ACTIONS(43), 1,
      anon_sym_COMMA,
    ACTIONS(41), 3,
      sym_float,
      sym_boolean,
      sym_date_time,
    STATE(47), 4,
      sym__basic_string_inline,
      sym__literal_string_inline,
      sym__multiline_basic_string,
      sym__multiline_literal_string,
    STATE(63), 4,
      sym__value,
      sym_string,
      sym_array,
      sym_inline_table,
  [96] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_RBRACK,
    ACTIONS(47), 1,
      sym_integer,
    ACTIONS(49), 3,
      sym_float,
      sym_boolean,
      sym_date_time,
    STATE(47), 4,
      sym__basic_string_inline,
      sym__literal_string_inline,
      sym__multiline_basic_string,
      sym__multiline_literal_string,
    STATE(81), 4,
      sym__value,
      sym_string,
      sym_array,
      sym_inline_table,
  [141] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      sym_integer,
    ACTIONS(51), 1,
      anon_sym_RBRACK,
    ACTIONS(49), 3,
      sym_float,
      sym_boolean,
      sym_date_time,
    STATE(47), 4,
      sym__basic_string_inline,
      sym__literal_string_inline,
      sym__multiline_basic_string,
      sym__multiline_literal_string,
    STATE(81), 4,
      sym__value,
      sym_string,
      sym_array,
      sym_inline_table,
  [186] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      sym_integer,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    ACTIONS(49), 3,
      sym_float,
      sym_boolean,
      sym_date_time,
    STATE(47), 4,
      sym__basic_string_inline,
      sym__literal_string_inline,
      sym__multiline_basic_string,
      sym__multiline_literal_string,
    STATE(81), 4,
      sym__value,
      sym_string,
      sym_array,
      sym_inline_table,
  [231] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      sym_integer,
    ACTIONS(55), 1,
      anon_sym_RBRACK,
    ACTIONS(49), 3,
      sym_float,
      sym_boolean,
      sym_date_time,
    STATE(47), 4,
      sym__basic_string_inline,
      sym__literal_string_inline,
      sym__multiline_basic_string,
      sym__multiline_literal_string,
    STATE(81), 4,
      sym__value,
      sym_string,
      sym_array,
      sym_inline_table,
  [276] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(67), 1,
      sym_integer,
    ACTIONS(71), 1,
      anon_sym_LBRACE,
    ACTIONS(69), 3,
      sym_float,
      sym_boolean,
      sym_date_time,
    STATE(91), 4,
      sym__basic_string_inline,
      sym__literal_string_inline,
      sym__multiline_basic_string,
      sym__multiline_literal_string,
    STATE(111), 4,
      sym__value,
      sym_string,
      sym_array,
      sym_inline_table,
  [318] = 13,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 1,
      sym__newline,
    ACTIONS(78), 1,
      sym_comment,
    ACTIONS(81), 1,
      sym_bare_key,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    ACTIONS(87), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(90), 1,
      anon_sym_DQUOTE,
    ACTIONS(93), 1,
      anon_sym_SQUOTE,
    STATE(9), 1,
      aux_sym_source_file_repeat1,
    STATE(87), 1,
      sym_key,
    STATE(42), 2,
      sym__basic_string_inline,
      sym__literal_string_inline,
    STATE(70), 3,
      sym__simple_key,
      sym_quoted_key,
      sym_dotted_key,
    STATE(95), 4,
      sym__expression,
      sym_key_value,
      sym_table,
      sym_array_of_tables,
  [364] = 13,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_bare_key,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    ACTIONS(98), 1,
      sym__newline,
    STATE(9), 1,
      aux_sym_source_file_repeat1,
    STATE(87), 1,
      sym_key,
    STATE(42), 2,
      sym__basic_string_inline,
      sym__literal_string_inline,
    STATE(70), 3,
      sym__simple_key,
      sym_quoted_key,
      sym_dotted_key,
    STATE(95), 4,
      sym__expression,
      sym_key_value,
      sym_table,
      sym_array_of_tables,
  [410] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      sym_integer,
    ACTIONS(49), 3,
      sym_float,
      sym_boolean,
      sym_date_time,
    STATE(47), 4,
      sym__basic_string_inline,
      sym__literal_string_inline,
      sym__multiline_basic_string,
      sym__multiline_literal_string,
    STATE(81), 4,
      sym__value,
      sym_string,
      sym_array,
      sym_inline_table,
  [452] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(100), 1,
      sym_integer,
    ACTIONS(102), 3,
      sym_float,
      sym_boolean,
      sym_date_time,
    STATE(47), 4,
      sym__basic_string_inline,
      sym__literal_string_inline,
      sym__multiline_basic_string,
      sym__multiline_literal_string,
    STATE(85), 4,
      sym__value,
      sym_string,
      sym_array,
      sym_inline_table,
  [494] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym_bare_key,
    ACTIONS(106), 1,
      anon_sym_DQUOTE,
    ACTIONS(108), 1,
      anon_sym_SQUOTE,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      sym_inline_key_value,
    STATE(83), 1,
      sym_key,
    STATE(42), 2,
      sym__basic_string_inline,
      sym__literal_string_inline,
    STATE(70), 3,
      sym__simple_key,
      sym_quoted_key,
      sym_dotted_key,
  [525] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym_bare_key,
    ACTIONS(106), 1,
      anon_sym_DQUOTE,
    ACTIONS(108), 1,
      anon_sym_SQUOTE,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      sym_inline_key_value,
    STATE(83), 1,
      sym_key,
    STATE(42), 2,
      sym__basic_string_inline,
      sym__literal_string_inline,
    STATE(70), 3,
      sym__simple_key,
      sym_quoted_key,
      sym_dotted_key,
  [556] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym_bare_key,
    ACTIONS(106), 1,
      anon_sym_DQUOTE,
    ACTIONS(108), 1,
      anon_sym_SQUOTE,
    STATE(83), 1,
      sym_key,
    STATE(86), 1,
      sym_inline_key_value,
    STATE(42), 2,
      sym__basic_string_inline,
      sym__literal_string_inline,
    STATE(70), 3,
      sym__simple_key,
      sym_quoted_key,
      sym_dotted_key,
  [584] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym_bare_key,
    ACTIONS(106), 1,
      anon_sym_DQUOTE,
    ACTIONS(108), 1,
      anon_sym_SQUOTE,
    STATE(80), 1,
      sym_key,
    STATE(42), 2,
      sym__basic_string_inline,
      sym__literal_string_inline,
    STATE(70), 3,
      sym__simple_key,
      sym_quoted_key,
      sym_dotted_key,
  [609] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_bare_key,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      anon_sym_SQUOTE,
    STATE(82), 1,
      sym_key,
    STATE(89), 2,
      sym__basic_string_inline,
      sym__literal_string_inline,
    STATE(88), 3,
      sym__simple_key,
      sym_quoted_key,
      sym_dotted_key,
  [634] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_DQUOTE,
    ACTIONS(108), 1,
      anon_sym_SQUOTE,
    ACTIONS(120), 1,
      sym_bare_key,
    STATE(33), 2,
      sym__simple_key,
      sym_quoted_key,
    STATE(42), 2,
      sym__basic_string_inline,
      sym__literal_string_inline,
  [655] = 2,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      sym__newline,
    ACTIONS(122), 6,
      sym_comment,
      sym_bare_key,
      anon_sym_LBRACK,
      anon_sym_LBRACK_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [668] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      anon_sym_SQUOTE,
    ACTIONS(124), 1,
      sym_bare_key,
    STATE(75), 2,
      sym__simple_key,
      sym_quoted_key,
    STATE(89), 2,
      sym__basic_string_inline,
      sym__literal_string_inline,
  [689] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 5,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [700] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 5,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [711] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 5,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [722] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 5,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [733] = 4,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_DQUOTE,
    STATE(26), 1,
      aux_sym__basic_string_inline_repeat1,
    ACTIONS(138), 2,
      aux_sym__basic_string_inline_token1,
      sym_escape_sequence,
  [747] = 4,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      aux_sym__basic_string_inline_repeat1,
    ACTIONS(142), 2,
      aux_sym__basic_string_inline_token1,
      sym_escape_sequence,
  [761] = 4,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      aux_sym__basic_string_inline_repeat1,
    ACTIONS(146), 2,
      aux_sym__basic_string_inline_token1,
      sym_escape_sequence,
  [775] = 4,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      aux_sym__basic_string_inline_repeat1,
    ACTIONS(151), 2,
      aux_sym__basic_string_inline_token1,
      sym_escape_sequence,
  [789] = 4,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      aux_sym__basic_string_inline_repeat1,
    ACTIONS(142), 2,
      aux_sym__basic_string_inline_token1,
      sym_escape_sequence,
  [803] = 4,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(31), 1,
      aux_sym__basic_string_inline_repeat1,
    ACTIONS(157), 2,
      aux_sym__basic_string_inline_token1,
      sym_escape_sequence,
  [817] = 4,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      aux_sym__basic_string_inline_repeat1,
    ACTIONS(142), 2,
      aux_sym__basic_string_inline_token1,
      sym_escape_sequence,
  [831] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(163), 1,
      sym__multiline_basic_string_content,
    STATE(40), 1,
      aux_sym__multiline_basic_string_repeat1,
  [844] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 3,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_RBRACK,
  [853] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_RBRACK,
    ACTIONS(169), 1,
      anon_sym_COMMA,
    STATE(39), 1,
      aux_sym_array_repeat1,
  [866] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym__multiline_basic_string_content,
    ACTIONS(171), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(40), 1,
      aux_sym__multiline_basic_string_repeat1,
  [879] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(175), 1,
      sym__multiline_literal_string_content,
    STATE(41), 1,
      aux_sym__multiline_literal_string_repeat1,
  [892] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(179), 1,
      anon_sym_RBRACE,
    STATE(43), 1,
      aux_sym_inline_table_repeat1,
  [905] = 4,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      aux_sym__literal_string_inline_token1,
    STATE(62), 1,
      aux_sym__literal_string_inline_repeat1,
  [918] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_RBRACK,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym_array_repeat1,
  [931] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(189), 1,
      sym__multiline_basic_string_content,
    STATE(40), 1,
      aux_sym__multiline_basic_string_repeat1,
  [944] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(194), 1,
      sym__multiline_literal_string_content,
    STATE(41), 1,
      aux_sym__multiline_literal_string_repeat1,
  [957] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 3,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_RBRACK,
  [966] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      aux_sym_inline_table_repeat1,
  [979] = 4,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_SQUOTE,
    ACTIONS(203), 1,
      aux_sym__literal_string_inline_token1,
    STATE(38), 1,
      aux_sym__literal_string_inline_repeat1,
  [992] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_RBRACK,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym_array_repeat1,
  [1005] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_COMMA,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      aux_sym_inline_table_repeat1,
  [1018] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 3,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1027] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 3,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1036] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 3,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1045] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 3,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1054] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 3,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1063] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 3,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1072] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 3,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1081] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 3,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1090] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 3,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1099] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 3,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1108] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 3,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1117] = 4,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_SQUOTE,
    ACTIONS(239), 1,
      aux_sym__literal_string_inline_token1,
    STATE(59), 1,
      aux_sym__literal_string_inline_repeat1,
  [1130] = 4,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(183), 1,
      aux_sym__literal_string_inline_token1,
    ACTIONS(241), 1,
      anon_sym_SQUOTE,
    STATE(62), 1,
      aux_sym__literal_string_inline_repeat1,
  [1143] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym__multiline_basic_string_content,
    ACTIONS(243), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(32), 1,
      aux_sym__multiline_basic_string_repeat1,
  [1156] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym__multiline_literal_string_content,
    ACTIONS(245), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    STATE(64), 1,
      aux_sym__multiline_literal_string_repeat1,
  [1169] = 4,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_SQUOTE,
    ACTIONS(249), 1,
      aux_sym__literal_string_inline_token1,
    STATE(62), 1,
      aux_sym__literal_string_inline_repeat1,
  [1182] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_RBRACK,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_array_repeat1,
  [1195] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym__multiline_literal_string_content,
    ACTIONS(256), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    STATE(41), 1,
      aux_sym__multiline_literal_string_repeat1,
  [1208] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(258), 1,
      anon_sym_RBRACE,
    STATE(68), 1,
      aux_sym_inline_table_repeat1,
  [1221] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym__multiline_basic_string_content,
    ACTIONS(260), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(35), 1,
      aux_sym__multiline_basic_string_repeat1,
  [1234] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym_array_repeat1,
  [1247] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      aux_sym_inline_table_repeat1,
  [1260] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym__multiline_literal_string_content,
    ACTIONS(266), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    STATE(36), 1,
      aux_sym__multiline_literal_string_repeat1,
  [1273] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 3,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_RBRACK,
  [1282] = 4,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_SQUOTE,
    ACTIONS(272), 1,
      aux_sym__literal_string_inline_token1,
    STATE(72), 1,
      aux_sym__literal_string_inline_repeat1,
  [1295] = 4,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(183), 1,
      aux_sym__literal_string_inline_token1,
    ACTIONS(274), 1,
      anon_sym_SQUOTE,
    STATE(62), 1,
      aux_sym__literal_string_inline_repeat1,
  [1308] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 3,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1317] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 2,
      anon_sym_DOT,
      anon_sym_RBRACK_RBRACK,
  [1325] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 2,
      anon_sym_DOT,
      anon_sym_RBRACK_RBRACK,
  [1333] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 2,
      sym__multiline_literal_string_content,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
  [1341] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 2,
      anon_sym_DOT,
      anon_sym_RBRACK_RBRACK,
  [1349] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 2,
      anon_sym_DOT,
      anon_sym_RBRACK_RBRACK,
  [1357] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 2,
      anon_sym_DOT,
      anon_sym_RBRACK_RBRACK,
  [1365] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_DOT,
    ACTIONS(282), 1,
      anon_sym_RBRACK,
  [1375] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 2,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1383] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_DOT,
    ACTIONS(286), 1,
      anon_sym_RBRACK_RBRACK,
  [1393] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_DOT,
    ACTIONS(288), 1,
      anon_sym_EQ,
  [1403] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 2,
      sym__multiline_basic_string_content,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
  [1411] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1419] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1427] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_DOT,
    ACTIONS(294), 1,
      anon_sym_EQ,
  [1437] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 2,
      anon_sym_DOT,
      anon_sym_RBRACK_RBRACK,
  [1445] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_DOT,
      anon_sym_RBRACK_RBRACK,
  [1453] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym__newline,
  [1460] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(215), 1,
      sym__newline,
  [1467] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(227), 1,
      sym__newline,
  [1474] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym__newline,
  [1481] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(276), 1,
      sym__newline,
  [1488] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(296), 1,
      sym__newline,
  [1495] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      ts_builtin_sym_end,
  [1502] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym__newline,
  [1509] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(221), 1,
      sym__newline,
  [1516] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym__newline,
  [1523] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_RBRACK,
  [1530] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym__newline,
  [1537] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_RBRACK,
  [1544] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(217), 1,
      sym__newline,
  [1551] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym__newline,
  [1558] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(300), 1,
      sym__newline,
  [1565] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym__newline,
  [1572] = 2,
    ACTIONS(132), 1,
      sym__newline,
    ACTIONS(134), 1,
      sym_comment,
  [1579] = 2,
    ACTIONS(126), 1,
      sym__newline,
    ACTIONS(134), 1,
      sym_comment,
  [1586] = 2,
    ACTIONS(128), 1,
      sym__newline,
    ACTIONS(134), 1,
      sym_comment,
  [1593] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(302), 1,
      sym__newline,
  [1600] = 2,
    ACTIONS(134), 1,
      sym_comment,
    ACTIONS(304), 1,
      sym__newline,
  [1607] = 2,
    ACTIONS(130), 1,
      sym__newline,
    ACTIONS(134), 1,
      sym_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 141,
  [SMALL_STATE(6)] = 186,
  [SMALL_STATE(7)] = 231,
  [SMALL_STATE(8)] = 276,
  [SMALL_STATE(9)] = 318,
  [SMALL_STATE(10)] = 364,
  [SMALL_STATE(11)] = 410,
  [SMALL_STATE(12)] = 452,
  [SMALL_STATE(13)] = 494,
  [SMALL_STATE(14)] = 525,
  [SMALL_STATE(15)] = 556,
  [SMALL_STATE(16)] = 584,
  [SMALL_STATE(17)] = 609,
  [SMALL_STATE(18)] = 634,
  [SMALL_STATE(19)] = 655,
  [SMALL_STATE(20)] = 668,
  [SMALL_STATE(21)] = 689,
  [SMALL_STATE(22)] = 700,
  [SMALL_STATE(23)] = 711,
  [SMALL_STATE(24)] = 722,
  [SMALL_STATE(25)] = 733,
  [SMALL_STATE(26)] = 747,
  [SMALL_STATE(27)] = 761,
  [SMALL_STATE(28)] = 775,
  [SMALL_STATE(29)] = 789,
  [SMALL_STATE(30)] = 803,
  [SMALL_STATE(31)] = 817,
  [SMALL_STATE(32)] = 831,
  [SMALL_STATE(33)] = 844,
  [SMALL_STATE(34)] = 853,
  [SMALL_STATE(35)] = 866,
  [SMALL_STATE(36)] = 879,
  [SMALL_STATE(37)] = 892,
  [SMALL_STATE(38)] = 905,
  [SMALL_STATE(39)] = 918,
  [SMALL_STATE(40)] = 931,
  [SMALL_STATE(41)] = 944,
  [SMALL_STATE(42)] = 957,
  [SMALL_STATE(43)] = 966,
  [SMALL_STATE(44)] = 979,
  [SMALL_STATE(45)] = 992,
  [SMALL_STATE(46)] = 1005,
  [SMALL_STATE(47)] = 1018,
  [SMALL_STATE(48)] = 1027,
  [SMALL_STATE(49)] = 1036,
  [SMALL_STATE(50)] = 1045,
  [SMALL_STATE(51)] = 1054,
  [SMALL_STATE(52)] = 1063,
  [SMALL_STATE(53)] = 1072,
  [SMALL_STATE(54)] = 1081,
  [SMALL_STATE(55)] = 1090,
  [SMALL_STATE(56)] = 1099,
  [SMALL_STATE(57)] = 1108,
  [SMALL_STATE(58)] = 1117,
  [SMALL_STATE(59)] = 1130,
  [SMALL_STATE(60)] = 1143,
  [SMALL_STATE(61)] = 1156,
  [SMALL_STATE(62)] = 1169,
  [SMALL_STATE(63)] = 1182,
  [SMALL_STATE(64)] = 1195,
  [SMALL_STATE(65)] = 1208,
  [SMALL_STATE(66)] = 1221,
  [SMALL_STATE(67)] = 1234,
  [SMALL_STATE(68)] = 1247,
  [SMALL_STATE(69)] = 1260,
  [SMALL_STATE(70)] = 1273,
  [SMALL_STATE(71)] = 1282,
  [SMALL_STATE(72)] = 1295,
  [SMALL_STATE(73)] = 1308,
  [SMALL_STATE(74)] = 1317,
  [SMALL_STATE(75)] = 1325,
  [SMALL_STATE(76)] = 1333,
  [SMALL_STATE(77)] = 1341,
  [SMALL_STATE(78)] = 1349,
  [SMALL_STATE(79)] = 1357,
  [SMALL_STATE(80)] = 1365,
  [SMALL_STATE(81)] = 1375,
  [SMALL_STATE(82)] = 1383,
  [SMALL_STATE(83)] = 1393,
  [SMALL_STATE(84)] = 1403,
  [SMALL_STATE(85)] = 1411,
  [SMALL_STATE(86)] = 1419,
  [SMALL_STATE(87)] = 1427,
  [SMALL_STATE(88)] = 1437,
  [SMALL_STATE(89)] = 1445,
  [SMALL_STATE(90)] = 1453,
  [SMALL_STATE(91)] = 1460,
  [SMALL_STATE(92)] = 1467,
  [SMALL_STATE(93)] = 1474,
  [SMALL_STATE(94)] = 1481,
  [SMALL_STATE(95)] = 1488,
  [SMALL_STATE(96)] = 1495,
  [SMALL_STATE(97)] = 1502,
  [SMALL_STATE(98)] = 1509,
  [SMALL_STATE(99)] = 1516,
  [SMALL_STATE(100)] = 1523,
  [SMALL_STATE(101)] = 1530,
  [SMALL_STATE(102)] = 1537,
  [SMALL_STATE(103)] = 1544,
  [SMALL_STATE(104)] = 1551,
  [SMALL_STATE(105)] = 1558,
  [SMALL_STATE(106)] = 1565,
  [SMALL_STATE(107)] = 1572,
  [SMALL_STATE(108)] = 1579,
  [SMALL_STATE(109)] = 1586,
  [SMALL_STATE(110)] = 1593,
  [SMALL_STATE(111)] = 1600,
  [SMALL_STATE(112)] = 1607,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__basic_string_inline, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal_string_inline, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__basic_string_inline, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal_string_inline, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__basic_string_inline_repeat1, 2, 0, 0),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__basic_string_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_key, 3, 0, 4),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__multiline_basic_string_repeat1, 2, 0, 0),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__multiline_basic_string_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__multiline_literal_string_repeat1, 2, 0, 0),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__multiline_literal_string_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_key, 1, 0, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inline_table_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_inline_table_repeat1, 2, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_basic_string, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_literal_string, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_table, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_basic_string, 3, 0, 5),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_literal_string, 3, 0, 5),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_table, 3, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_table, 4, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__literal_string_inline_repeat1, 2, 0, 0),
  [249] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__literal_string_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [274] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__multiline_literal_string_repeat1, 1, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__multiline_basic_string_repeat1, 1, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_key_value, 3, 0, 3),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [298] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 3, 0, 2),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_of_tables, 3, 0, 2),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value, 3, 0, 3),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__multiline_basic_string_content = 0,
  ts_external_token__multiline_literal_string_content = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__multiline_basic_string_content] = sym__multiline_basic_string_content,
  [ts_external_token__multiline_literal_string_content] = sym__multiline_literal_string_content,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__multiline_basic_string_content] = true,
    [ts_external_token__multiline_literal_string_content] = true,
  },
  [2] = {
    [ts_external_token__multiline_basic_string_content] = true,
  },
  [3] = {
    [ts_external_token__multiline_literal_string_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_toml_external_scanner_create(void);
void tree_sitter_toml_external_scanner_destroy(void *);
bool tree_sitter_toml_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_toml_external_scanner_serialize(void *, char *);
void tree_sitter_toml_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_toml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_toml_external_scanner_create,
      tree_sitter_toml_external_scanner_destroy,
      tree_sitter_toml_external_scanner_scan,
      tree_sitter_toml_external_scanner_serialize,
      tree_sitter_toml_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "toml",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
